s = '''
[sunder~="bg_\#bdd9f5"]{background:#bdd9f5;}
[sunder~="m_0"]{margin:0;}
[sunder~="p_0"]{padding:0;}
[sunder~="font\-family_'Assistant'\,\`sans\-serif"]{font-family:'Assistant', sans-serif;}
[sunder~="ov_hidden"]{overflow:hidden;}
[sunder~="position_absolute"]{position:absolute;}
[sunder~="h_100\%"]{height:100%;}
[sunder~="w_100\%"]{width:100%;}
[sunder~="bg_\#d65076"]{background:#d65076;}
[sunder~="z_5"]{z-index:5;}
[sunder~="dis_grid"]{display:grid;}
[sunder~="pli_center"]{place-items:center;}
[sunder~="c_white"]{color:white;}
[sunder~="ftw_900"]{font-weight:900;}
[sunder~="ftsz_3rem"]{font-size:3rem;}
[sunder~="dis_flex"]{display:flex;}
[sunder~="w_fit\-content"]{width:fit-content;}
[sunder~="mx_auto"]{margin-inline:auto;}
[sunder~="position_relative"]{position:relative;}
[sunder~="top_\-100vh"]{top:-100vh;}
[sunder~="trndu_2s"]{transition-duration:2s;}@keyframes \&float_2rem_5rem{0%{transform:translateY(2rem);}50%{transform:translateY(5rem);}100%{transform:translateY(2rem);}}
[sunder~="a_&float_2rem_5rem\`5s\`ease\`infinite"]{animation:\&float_2rem_5rem 5s ease infinite;}
[sunder~="fd_column"]{flex-direction:column;}
[sunder~="w_\.2rem"]{width:.2rem;}
[sunder~="h_fit\-content"]{height:fit-content;}
[sunder~="top_2rem"]{top:2rem;}
[sunder~="mt_1rem"]{margin-top:1rem;}
[sunder~="h_2rem"]{height:2rem;}
[sunder~="bg_\#fad7bd"]{background:#fad7bd;}
[sunder~="bsh_0\`0\`1px\`grey"]{box-shadow:0 0 1px grey;}
[sunder~="z_2"]{z-index:2;}
[sunder~="top_5rem"]{top:5rem;}
[sunder~="h_3rem"]{height:3rem;}
[sunder~="h_4rem"]{height:4rem;}
[sunder~="w_350px"]{width:350px;}
[sunder~="h_712px"]{height:712px;}
[sunder~="bg_black"]{background:black;}
[sunder~="mx_5px"]{margin-inline:5px;}
[sunder~="my_5\%"]{margin-block:5%;}
[sunder~="brad_60px"]{border-radius:60px;}
[sunder~="bsh_0\`0\`20px"]{box-shadow:0 0 20px;}
[sunder~="border_10px\`solid\`black"]{border:10px solid black;}
[sunder~="out_3px\`solid\`\#fad7bd"]{outline:3px solid #fad7bd;}
[sunder~="\$filter"]{filter:hue-rotate(var(--hr)) invert(var(--in)) grayscale(var(--gs)) blur(var(--bl)) opacity(var(--op)) contrast(var(--cn)) brightness(var(--bh));--op:1;--bl:0;--gs:0;--in:0;--bh:1;--cn:1;--hr:0;}
[sunder~="\$bright_110"]{--bh:110%;}
[sunder~="top_0"]{top:0;}
[sunder~="left_0"]{left:0;}
[sunder~="right_0"]{right:0;}
[sunder~="h_30px"]{height:30px;}
[sunder~="brad_0\`0\`20px\`20px"]{border-radius:0 0 20px 20px;}
[sunder~="w_140px"]{width:140px;}
[sunder~="top_50\%"]{top:50%;}
[sunder~="bg_rgb\(white\,10\%\)"]{background:rgb(white,10%);}
[sunder~="h_\.3rem"]{height:.3rem;}
[sunder~="w_30\%"]{width:30%;}
[sunder~="jc_end"]{justify-content:end;}
[sunder~="\:\^&>\*\:ml_\.5rem"]{&>*{margin-left:.5rem;}}
[sunder~="mr_1\.5rem"]{margin-right:1.5rem;}
[sunder~="mt_\.25rem"]{margin-top:.25rem;}
[sunder~="h_1rem"]{height:1rem;}
[sunder~="w_1rem"]{width:1rem;}
[sunder~="h_2px"]{height:2px;}
[sunder~="w_4\.5rem"]{width:4.5rem;}
[sunder~="ml_auto"]{margin-left:auto;}
[sunder~="bg_white"]{background:white;}
[sunder~="mt_\.5rem"]{margin-top:.5rem;}
[sunder~="ai_center"]{align-items:center;}
[sunder~="ftsz_5rem"]{font-size:5rem;}
[sunder~="ftw_200"]{font-weight:200;}
[sunder~="ftsz_1rem"]{font-size:1rem;}
[sunder~="ftw_700"]{font-weight:700;}
[sunder~="mx_\.5rem"]{margin-inline:.5rem;}
[sunder~="tr_scale\(\.90\)"]{transform:scale(.90);}
[sunder~="tro_bottom"]{transform-origin:bottom;}
[sunder~="bt_\-\.875rem"]{bottom:-.875rem;}
[sunder~="l_0"]{left:0;}
[sunder~="r_0"]{right:0;}
[sunder~="bg_rgba\(white\,\.2\)"]{background:rgba(white,.2);}
[sunder~="p_1rem"]{padding:1rem;}
[sunder~="backdrop\-filter_blur\(5px\)"]{backdrop-filter:blur(5px);}
[sunder~="brad_0\`0\`25px\`25px"]{border-radius:0 0 25px 25px;}
[sunder~="tr_scale\(\.95\)"]{transform:scale(.95);}
[sunder~="bt_\-\.5rem"]{bottom:-.5rem;}
[sunder~="bg_rgba\(white\,\.3\)"]{background:rgba(white,.3);}
[sunder~="h_auto"]{height:auto;}
[sunder~="bg_rgba\(white\,\.5\)"]{background:rgba(white,.5);}
[sunder~="pb_\.25rem"]{padding-bottom:.25rem;}
[sunder~="brad_25px"]{border-radius:25px;}
[sunder~="jc_space\-between"]{justify-content:space-between;}
[sunder~="ftw_bold"]{font-weight:bold;}
[sunder~="\:hover\:h_3rem"]{&:hover{height:3rem;}}
[sunder~="ftsz_1\.5rem"]{font-size:1.5rem;}
[sunder~="bg_\#5e6873"]{background:#5e6873;}
[sunder~="w_2rem"]{width:2rem;}
[sunder~="brad_100\%"]{border-radius:100%;}
[sunder~="jc_center"]{justify-content:center;}
[sunder~="gap_\.5rem"]{gap:.5rem;}
[sunder~="brad_5px"]{border-radius:5px;}
[sunder~="mb_\.25rem"]{margin-bottom:.25rem;}
[sunder~="mt_\.75rem"]{margin-top:.75rem;}
[sunder~="ftsz_\.75rem"]{font-size:.75rem;}
[sunder~="ftw_500"]{font-weight:500;}
[sunder~="bcol_rgb\(black\,20\%\)"]{border-color:rgb(black,20%);}
[sunder~="gtc_repeat\(3\,minmax\(0\,1fr\)\)"]{grid-template-columns:repeat(3,minmax(0,1fr));}
[sunder~="gap_\.25rem"]{gap:.25rem;}
[sunder~="ai_end"]{align-items:end;}
[sunder~="gc_span\`2/span\`2"]{grid-column:span 2/span 2;}
[sunder~="ftsz_\.875rem"]{font-size:.875rem;}
[sunder~="lh_1\.25rem"]{line-height:1.25rem;}
[sunder~="mt_\.1rem"]{margin-top:.1rem;}
[sunder~="lh_1rem"]{line-height:1rem;}
[sunder~="mb_0"]{margin-bottom:0;}
[sunder~="fd_row\-reverse"]{flex-direction:row-reverse;}
[sunder~="\:\^&>\*\:mr_\-\.5rem"]{&>*{margin-right:-.5rem;}}
[sunder~="lsy_none"]{list-style:none;}
[sunder~="mr_0"]{margin-right:0;}
[sunder~="object\-fit_cover"]{object-fit:cover;}
[sunder~="brad_25\%"]{border-radius:25%;}
[sunder~="bg_cyan"]{background:cyan;}
[sunder~="bt_0"]{bottom:0;}
[sunder~="h_5rem"]{height:5rem;}
[sunder~="px_2\.5rem"]{padding-inline:2.5rem;}
[sunder~="bg_rgb\(white\,20\%\)"]{background:rgb(white,20%);}
[sunder~="p_\.5rem"]{padding:.5rem;}
[sunder~="w_1\.95rem"]{width:1.95rem;}
[sunder~="h_1\.95rem"]{height:1.95rem;}
[sunder~="cur_pointer"]{cursor:pointer;}
[sunder~="\:h\:bg_rgb\(white\,40\%\)"]{&:hover{background:rgb(white,40%);}}
[sunder~="h_1\.5rem"]{height:1.5rem;}
[sunder~="w_1\.5rem"]{width:1.5rem;}
[sunder~="bottom_1\%"]{bottom:1%;}
[sunder~="h_5px"]{height:5px;}
[sunder~="brad_20px"]{border-radius:20px;}
[sunder~="bg_rgb\(white\,80\%\)"]{background:rgb(white,80%);}
[sunder~="\:h\:bg_white"]{&:hover{background:white;}}
[sunder~="top_6rem"]{top:6rem;}
[sunder~="top_8rem"]{top:8rem;}'''

x = s.split("\n")

for i in x:
    if("{&" in i):
        i = i.replace("&",i[0:i.find("]")+1])
        i = i[i.find("{")+1:]
        print(i)